name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
    - uses: actions/checkout@v4

    - name: Install clang19
      run: |
        sudo apt update
        sudo apt install -y clang-19

    - name: Run Make
      run: make
